### ISSUE TITLE
Can't install UMM

### ISSUE THREAD

**Issue by CharlesK2007** [Hydraxous/Configgy#7]
I simply can't install UMM. I followed every single step correctly, I already had BepinEX and Configgy installed previously so they couldn't be what was causing the problem. I placed each folder in the correct directories (UMM in "plugins" folder and UMM Mods in "BepinEX" folder), I even tried to place the extra UMM.dl in both folders just to be safe and UMM still didn't show up.

And just in case you ask: yes, I rebooted the game between each change I made.
What the fuck am I doing wrong?

**Comment by Hydraxous** [comment]
Firstly, this issue is not related to Configgy so I'm going to close it.

Second, you aren't making an installation mistake.
UMM has been deprecated, is no longer functional, and will not be updated.
